# Netlify Configuration for MTG Marketplace
# This configuration handles both frontend (Vue.js) and backend (Express.js API) deployment

[build]
  # Base directory for the build
  base = "frontend"
  
  # Build command for the frontend
  command = "npm install && npm run build"
  
  # Directory to publish (Vite builds to 'dist' by default)
  publish = "dist"
  
  # Node version
  [build.environment]
    NODE_VERSION = "18"
    NPM_VERSION = "8"

# Redirect all API calls to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# SPA fallback - redirect all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Functions configuration for the backend API
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  
  # Set environment variables for functions
  [functions.environment]
    NODE_ENV = "production"

# Build plugins
[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Context-specific settings
[context.production]
  command = "npm run build"
  [context.production.environment]
    NODE_ENV = "production"

[context.deploy-preview]
  command = "npm run build"

[context.branch-deploy]
  command = "npm run build"

# Development context
[context.dev]
  command = "npm run dev"
  
# Environment variables (these need to be set in Netlify UI)
# Required environment variables:
# - VITE_SUPABASE_URL
# - VITE_SUPABASE_ANON_KEY
# - SUPABASE_URL
# - SUPABASE_SECRET_KEY
# - JWT_SECRET
# - STRIPE_SECRET_KEY (if using Stripe)
# - SMTP_HOST
# - SMTP_PORT
# - SMTP_USER
# - SMTP_PASS
# - FROM_EMAIL
# - EASYPOST_API_KEY (if using EasyPost for shipping)