# render.yaml - Render deployment configuration for MTG Marketplace
# This file defines infrastructure as code for automatic deployment

services:
  # Backend API Service
  - type: web
    name: mtg-marketplace-backend
    runtime: node
    region: oregon
    plan: free
    branch: master
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: SUPABASE_URL
        sync: false  # Set in Render Dashboard
      - key: SUPABASE_SECRET_KEY
        sync: false  # Set in Render Dashboard
      - key: SUPABASE_ANON_KEY
        sync: false  # Set in Render Dashboard
      - key: JWT_SECRET
        generateValue: true  # Render will auto-generate
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_SECURE
        value: false
      - key: FROM_EMAIL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: HELCIM_API_TOKEN
        sync: false
      - key: HELCIM_ACCOUNT_ID
        sync: false
      - key: HELCIM_TERMINAL_ID
        sync: false
      - key: EASYPOST_API_KEY
        sync: false
      - key: ENABLE_CRON_JOBS
        value: true
    healthCheckPath: /api/health
    autoDeploy: true
    
  # Frontend Static Site
  - type: web
    name: mtg-marketplace-frontend
    runtime: static
    plan: free
    branch: master
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://mtg-marketplace-backend.onrender.com
      - key: VITE_SUPABASE_URL
        sync: false  # Set in Render Dashboard
      - key: VITE_SUPABASE_ANON_KEY
        sync: false  # Set in Render Dashboard
      - key: VITE_STRIPE_PUBLISHABLE_KEY
        sync: false
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true

# Additional notes:
# 1. Update VITE_API_URL after backend deployment to use actual backend URL
# 2. All "sync: false" variables must be set in Render Dashboard
# 3. Consider adding a PostgreSQL or Redis service if needed
# 4. Review and adjust instance plans based on traffic needs